# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Flutter.gitlab-ci.yml

variables:
  FLUTTER_CHANNEL: "stable"
  FLUTTER_VERSION: "3.16.9"

install_flutter:
  stage: setup
  script:
    - apt-get update -q
    - apt-get install -y lib32stdc++6
    - git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL --depth 1
    - export PATH="$PATH:`pwd`/flutter/bin"
    - flutter doctor
    - flutter pub get
  artifacts:
    paths:
      - .flutter

code_quality:
  stage: test
  script:
    - metrics lib -r codeclimate  > gl-code-quality-report.json

test:
  stage: test
  script:
    - export PATH="$PATH:`pwd`/flutter/bin"
    - flutter test --coverage
  dependencies:
    - install_flutter

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production

