# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Flutter.gitlab-ci.yml

variables:
  FLUTTER_CHANNEL: "stable"
  FLUTTER_VERSION: "3.16.9"


test:
  stage: test
  image: "ghcr.io/cirruslabs/flutter:3.16.9"
  script:
    - export PATH="$PATH:`pwd`/flutter/bin"
    - flutter test --coverage
  


deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production

