# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Flutter.gitlab-ci.yml


stages:
  - test

variables:
  FLUTTER_CHANNEL: "stable"

before_script:
  - apt-get update -qy
  - apt-get install -y lib32stdc++6 libstdc++6
  - curl -sSL https://get.flutter.dev | sh
  - export PATH="$PATH:`pwd`/tortoise_world/flutter/bin/cache/dart-sdk/bin"
  - export PATH="$PATH:`pwd`/tortoise_world/flutter/bin"

cache:
  paths:
    - tortoise_world/.dart_tool/
    - tortoise_world/.packages/
    - tortoise_world/flutter/

test:
  stage: test
  script:
    - cd tortoise_world
    - flutter packages get
    - flutter test --coverage
  artifacts:
    paths:
      - tortoise_world/coverage/
  only:
    - main

