name: tortoise_world
description: "Application educative pour apprendre la programmation."

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  code_text_field: ^1.1.0
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

flutter:
  assets:
    - assets/images/

  uses-material-design: true
